### PR TITLE
Change CI Pipeline test matrix

### PR DESCRIPTION
**Pull request by nickmoreton**
Code base: https://projects.torchbox.com/projects/wordpress-to-wagtail-importer-package/tickets/90

This PR changes the versions of Django and Wagtail that tests are run on.

### CODE REVIEW

**Comment by nimasmi** [comment]
Django 3.1 security updates end on 1 December 2021. Is it worth supporting it still, when this package is not yet released?

Is there a reason we don't support Django 2.2 LTS?

**Comment by nickmoreton** [comment]
As seen with the 

> Django 3.1 security updates end on 1 December 2021. Is it worth supporting it still, when this package is not yet released?
> 
> Is there a reason we don't support Django 2.2 LTS?

I think early on we took out Django 2.2 because support in wagtail was removed in 2.14
https://docs.wagtail.io/en/stable/releases/upgrading.html

Looks like 2.15 still supports Django 3.1

**Comment by nimasmi** [comment]
You've now removed Wagtail 2.15. Why?

**Comment by nickmoreton** [comment]
> You've now removed Wagtail 2.15. Why?

The CI tests were failing with 2.15 but i've not had a chance to investigate that. Sorry should have mentioned that. https://github.com/torchbox/wagtail-wordpress-import/runs/4212124719?check_suite_focus=true

**Pull request merged**
